jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - run: npm ci

      - name: Copy code to app folder
        run: |
          rm -rf ~/node-app-cicd-aws-github-actions/*
          cp -r . ~/node-app-cicd-aws-github-actions

      - name: Restart app using PM2
        run: |
          cd ~/node-app-cicd-aws-github-actions
          node app.js
