name: Node.js CI/CD

# Trigger the workflow on pushes to the "main" branch
on:
  push:
    branches: ["main"]

jobs:
  build:
    # This job runs on a self-hosted runner, in this case, your EC2 instance
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the latest code from the GitHub repository
      - uses: actions/checkout@v4

      # Step 2: Setup Node.js environment using the specified version (e.g., 20.x)
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x" # Specify Node.js version
          cache: "npm"

      # Step 3: Install dependencies
      - run: npm ci

      # Step 4: Set up the environment variables by creating a .env file
      #         Secrets stored in GitHub will be used in the production environment
      # - run: |
      #     touch .env
      #     echo "${{ secrets.PROD_ENV }}" > .env

      # Step 5: Build the project (only if a build script is present in package.json)
      # - run: npm run build --if-present

    # Step 6: This step you have to update after setting up the nodejs application on ec2 instance
    #  Restart the Node.js app using PM2 for zero-downtime deployment
    - run: node app.js
