name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Remove old container
        run: sudo docker rm -f myapp-container || true

      - name: Run new container
        run: |
          sudo docker run -d -p 3000:3000 \
            -e PORT=${{ secrets.PORT }} \
            --name myapp-container ${{ secrets.DOCKER_USERNAME }}/myapp:latest
